version: "3"
services:
  frontend:
    build: ./frontend
    image: teithetsskalaen/frontend
    ports:
      - "7979:3000"
  backend:
    build: ./backend
    image: teithetsskalaen/backend
    ports:
      - "6969:6969"
    environment:
       DB_URL: "jdbc:postgresql://teithet-database:5432/postgres"
       DB_USERNAME: "postgres"
       DB_PASSWORD: "hemmelig"
    depends_on:
      - database
  database:
    image: "postgres:13"
    hostname: "teithet-database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_PASSWORD: "hemmelig"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local


